# http://wiki.ros.org/costmap_2d

rolling_window: true
track_unknown_space: true
width: 100
height: 100

plugins:
  - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}